/*!
 * \file unicode_scx.hpp
 * \brief Unicode Script_Extensions ranges for `\p{scx=...}` (UCD contract; NOT a partition).
 *
 * GENERATED by tools/gen_unicode_scx_tables.py -- DO NOT EDIT BY HAND.
 *
 * Parsed from the committed tools/ucd/Scripts.txt (base) + ScriptExtensions.txt (overrides),
 * UCD 16.0.0 (asserted, same version as Scripts.txt). Script_Extensions defaults to a code
 * point's own Script, EXCEPT the code points ScriptExtensions.txt overrides (a combining mark
 * shared across scripts, typically), whose scx REPLACES the default with an explicit set --
 * so, unlike script_ranges (a partition), a code point can be in several scripts' scx_ranges at
 * once, or none extra beyond its own Script. Indexed by the EXISTING real::detail::script enum
 * (unicode_script.hpp) -- no new enum, no new name resolver: `\p{sc=X}` and `\p{scx=X}` share
 * `resolve_script` (long name AND short UAX24 code), only the range table differs.
 */
#ifndef REAL_UNICODE_SCX_HPP
#define REAL_UNICODE_SCX_HPP

// Internal — do not include directly.
// Users: #include <real/real.hpp>, or a documented opt-in: <real/dfa.hpp>,
// <real/regex_set.hpp>, <real/compat/std/regex.hpp>, <real/compat/re2/re2.hpp>.

#include "real/version.hpp"

#include <cstddef>
#include <cstdint>
#include <span>

#include "real/core/program.hpp"           // code_range
#include "real/unicode/unicode_props.hpp"  // cp_in_ranges (contract-neutral binary search)
#include "real/unicode/unicode_script.hpp" // script (reused, not redefined)

namespace real::detail {

  inline constexpr const char* unicode_scx_unidata_version {"16.0.0"}; //!< The Unicode data version these tables were generated from.

  //! \brief `\p{scx=Adlam}` — 7 ranges, 92 code points.
  inline constexpr code_range scx_Adlam_ranges[] {
    {0x061F, 0x061F},
    {0x0640, 0x0640},
    {0x204F, 0x204F},
    {0x2E41, 0x2E41},
    {0x1E900, 0x1E94B},
    {0x1E950, 0x1E959},
    {0x1E95E, 0x1E95F},
  };

  //! \brief `\p{scx=Ahom}` — 3 ranges, 65 code points.
  inline constexpr code_range scx_Ahom_ranges[] {
    {0x11700, 0x1171A},
    {0x1171D, 0x1172B},
    {0x11730, 0x11746},
  };

  //! \brief `\p{scx=Anatolian_Hieroglyphs}` — 1 ranges, 583 code points.
  inline constexpr code_range scx_Anatolian_Hieroglyphs_ranges[] {
    {0x14400, 0x14646},
  };

  //! \brief `\p{scx=Arabic}` — 55 ranges, 1421 code points.
  inline constexpr code_range scx_Arabic_ranges[] {
    {0x0600, 0x0604},
    {0x0606, 0x06DC},
    {0x06DE, 0x06FF},
    {0x0750, 0x077F},
    {0x0870, 0x088E},
    {0x0890, 0x0891},
    {0x0897, 0x08E1},
    {0x08E3, 0x08FF},
    {0x204F, 0x204F},
    {0x2E41, 0x2E41},
    {0xFB50, 0xFBC2},
    {0xFBD3, 0xFD8F},
    {0xFD92, 0xFDC7},
    {0xFDCF, 0xFDCF},
    {0xFDF0, 0xFDFF},
    {0xFE70, 0xFE74},
    {0xFE76, 0xFEFC},
    {0x102E0, 0x102FB},
    {0x10E60, 0x10E7E},
    {0x10EC2, 0x10EC4},
    {0x10EFC, 0x10EFF},
    {0x1EE00, 0x1EE03},
    {0x1EE05, 0x1EE1F},
    {0x1EE21, 0x1EE22},
    {0x1EE24, 0x1EE24},
    {0x1EE27, 0x1EE27},
    {0x1EE29, 0x1EE32},
    {0x1EE34, 0x1EE37},
    {0x1EE39, 0x1EE39},
    {0x1EE3B, 0x1EE3B},
    {0x1EE42, 0x1EE42},
    {0x1EE47, 0x1EE47},
    {0x1EE49, 0x1EE49},
    {0x1EE4B, 0x1EE4B},
    {0x1EE4D, 0x1EE4F},
    {0x1EE51, 0x1EE52},
    {0x1EE54, 0x1EE54},
    {0x1EE57, 0x1EE57},
    {0x1EE59, 0x1EE59},
    {0x1EE5B, 0x1EE5B},
    {0x1EE5D, 0x1EE5D},
    {0x1EE5F, 0x1EE5F},
    {0x1EE61, 0x1EE62},
    {0x1EE64, 0x1EE64},
    {0x1EE67, 0x1EE6A},
    {0x1EE6C, 0x1EE72},
    {0x1EE74, 0x1EE77},
    {0x1EE79, 0x1EE7C},
    {0x1EE7E, 0x1EE7E},
    {0x1EE80, 0x1EE89},
    {0x1EE8B, 0x1EE9B},
    {0x1EEA1, 0x1EEA3},
    {0x1EEA5, 0x1EEA9},
    {0x1EEAB, 0x1EEBB},
    {0x1EEF0, 0x1EEF1},
  };

  //! \brief `\p{scx=Armenian}` — 5 ranges, 97 code points.
  inline constexpr code_range scx_Armenian_ranges[] {
    {0x0308, 0x0308},
    {0x0531, 0x0556},
    {0x0559, 0x058A},
    {0x058D, 0x058F},
    {0xFB13, 0xFB17},
  };

  //! \brief `\p{scx=Avestan}` — 4 ranges, 64 code points.
  inline constexpr code_range scx_Avestan_ranges[] {
    {0x00B7, 0x00B7},
    {0x2E30, 0x2E31},
    {0x10B00, 0x10B35},
    {0x10B39, 0x10B3F},
  };

  //! \brief `\p{scx=Balinese}` — 2 ranges, 127 code points.
  inline constexpr code_range scx_Balinese_ranges[] {
    {0x1B00, 0x1B4C},
    {0x1B4E, 0x1B7F},
  };

  //! \brief `\p{scx=Bamum}` — 2 ranges, 657 code points.
  inline constexpr code_range scx_Bamum_ranges[] {
    {0xA6A0, 0xA6F7},
    {0x16800, 0x16A38},
  };

  //! \brief `\p{scx=Bassa_Vah}` — 2 ranges, 36 code points.
  inline constexpr code_range scx_Bassa_Vah_ranges[] {
    {0x16AD0, 0x16AED},
    {0x16AF0, 0x16AF5},
  };

  //! \brief `\p{scx=Batak}` — 2 ranges, 56 code points.
  inline constexpr code_range scx_Batak_ranges[] {
    {0x1BC0, 0x1BF3},
    {0x1BFC, 0x1BFF},
  };

  //! \brief `\p{scx=Bengali}` — 27 ranges, 114 code points.
  inline constexpr code_range scx_Bengali_ranges[] {
    {0x02BC, 0x02BC},
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0980, 0x0983},
    {0x0985, 0x098C},
    {0x098F, 0x0990},
    {0x0993, 0x09A8},
    {0x09AA, 0x09B0},
    {0x09B2, 0x09B2},
    {0x09B6, 0x09B9},
    {0x09BC, 0x09C4},
    {0x09C7, 0x09C8},
    {0x09CB, 0x09CE},
    {0x09D7, 0x09D7},
    {0x09DC, 0x09DD},
    {0x09DF, 0x09E3},
    {0x09E6, 0x09FE},
    {0x1CD0, 0x1CD0},
    {0x1CD2, 0x1CD2},
    {0x1CD5, 0x1CD6},
    {0x1CD8, 0x1CD8},
    {0x1CE1, 0x1CE1},
    {0x1CEA, 0x1CEA},
    {0x1CED, 0x1CED},
    {0x1CF2, 0x1CF2},
    {0x1CF5, 0x1CF7},
    {0xA8F1, 0xA8F1},
  };

  //! \brief `\p{scx=Bhaiksuki}` — 4 ranges, 97 code points.
  inline constexpr code_range scx_Bhaiksuki_ranges[] {
    {0x11C00, 0x11C08},
    {0x11C0A, 0x11C36},
    {0x11C38, 0x11C45},
    {0x11C50, 0x11C6C},
  };

  //! \brief `\p{scx=Bopomofo}` — 15 ranges, 122 code points.
  inline constexpr code_range scx_Bopomofo_ranges[] {
    {0x02C7, 0x02C7},
    {0x02C9, 0x02CB},
    {0x02D9, 0x02D9},
    {0x02EA, 0x02EB},
    {0x3001, 0x3003},
    {0x3008, 0x3011},
    {0x3013, 0x301F},
    {0x302A, 0x302D},
    {0x3030, 0x3030},
    {0x3037, 0x3037},
    {0x30FB, 0x30FB},
    {0x3105, 0x312F},
    {0x31A0, 0x31BF},
    {0xFE45, 0xFE46},
    {0xFF61, 0xFF65},
  };

  //! \brief `\p{scx=Brahmi}` — 3 ranges, 115 code points.
  inline constexpr code_range scx_Brahmi_ranges[] {
    {0x11000, 0x1104D},
    {0x11052, 0x11075},
    {0x1107F, 0x1107F},
  };

  //! \brief `\p{scx=Braille}` — 1 ranges, 256 code points.
  inline constexpr code_range scx_Braille_ranges[] {
    {0x2800, 0x28FF},
  };

  //! \brief `\p{scx=Buginese}` — 3 ranges, 31 code points.
  inline constexpr code_range scx_Buginese_ranges[] {
    {0x1A00, 0x1A1B},
    {0x1A1E, 0x1A1F},
    {0xA9CF, 0xA9CF},
  };

  //! \brief `\p{scx=Buhid}` — 2 ranges, 22 code points.
  inline constexpr code_range scx_Buhid_ranges[] {
    {0x1735, 0x1736},
    {0x1740, 0x1753},
  };

  //! \brief `\p{scx=Canadian_Aboriginal}` — 3 ranges, 726 code points.
  inline constexpr code_range scx_Canadian_Aboriginal_ranges[] {
    {0x1400, 0x167F},
    {0x18B0, 0x18F5},
    {0x11AB0, 0x11ABF},
  };

  //! \brief `\p{scx=Carian}` — 5 ranges, 53 code points.
  inline constexpr code_range scx_Carian_ranges[] {
    {0x00B7, 0x00B7},
    {0x205A, 0x205A},
    {0x205D, 0x205D},
    {0x2E31, 0x2E31},
    {0x102A0, 0x102D0},
  };

  //! \brief `\p{scx=Caucasian_Albanian}` — 5 ranges, 56 code points.
  inline constexpr code_range scx_Caucasian_Albanian_ranges[] {
    {0x0304, 0x0304},
    {0x0331, 0x0331},
    {0x035E, 0x035E},
    {0x10530, 0x10563},
    {0x1056F, 0x1056F},
  };

  //! \brief `\p{scx=Chakma}` — 4 ranges, 91 code points.
  inline constexpr code_range scx_Chakma_ranges[] {
    {0x09E6, 0x09EF},
    {0x1040, 0x1049},
    {0x11100, 0x11134},
    {0x11136, 0x11147},
  };

  //! \brief `\p{scx=Cham}` — 4 ranges, 83 code points.
  inline constexpr code_range scx_Cham_ranges[] {
    {0xAA00, 0xAA36},
    {0xAA40, 0xAA4D},
    {0xAA50, 0xAA59},
    {0xAA5C, 0xAA5F},
  };

  //! \brief `\p{scx=Cherokee}` — 8 ranges, 182 code points.
  inline constexpr code_range scx_Cherokee_ranges[] {
    {0x0300, 0x0302},
    {0x0304, 0x0304},
    {0x030B, 0x030C},
    {0x0323, 0x0324},
    {0x0330, 0x0331},
    {0x13A0, 0x13F5},
    {0x13F8, 0x13FD},
    {0xAB70, 0xABBF},
  };

  //! \brief `\p{scx=Chorasmian}` — 1 ranges, 28 code points.
  inline constexpr code_range scx_Chorasmian_ranges[] {
    {0x10FB0, 0x10FCB},
  };

  //! \brief `\p{scx=Common}` — 159 ranges, 8585 code points.
  inline constexpr code_range scx_Common_ranges[] {
    {0x0000, 0x0040},
    {0x005B, 0x0060},
    {0x007B, 0x00A9},
    {0x00AB, 0x00B6},
    {0x00B8, 0x00B9},
    {0x00BB, 0x00BF},
    {0x00D7, 0x00D7},
    {0x00F7, 0x00F7},
    {0x02B9, 0x02BB},
    {0x02BD, 0x02C6},
    {0x02C8, 0x02C8},
    {0x02CC, 0x02CC},
    {0x02CE, 0x02D6},
    {0x02D8, 0x02D8},
    {0x02DA, 0x02DF},
    {0x02E5, 0x02E9},
    {0x02EC, 0x02FF},
    {0x037E, 0x037E},
    {0x0385, 0x0385},
    {0x0387, 0x0387},
    {0x0605, 0x0605},
    {0x06DD, 0x06DD},
    {0x08E2, 0x08E2},
    {0x0E3F, 0x0E3F},
    {0x0FD5, 0x0FD8},
    {0x2000, 0x200B},
    {0x200E, 0x202E},
    {0x2030, 0x204E},
    {0x2050, 0x2059},
    {0x205B, 0x205C},
    {0x205E, 0x2064},
    {0x2066, 0x2070},
    {0x2074, 0x207E},
    {0x2080, 0x208E},
    {0x20A0, 0x20C0},
    {0x2100, 0x2125},
    {0x2127, 0x2129},
    {0x212C, 0x2131},
    {0x2133, 0x214D},
    {0x214F, 0x215F},
    {0x2189, 0x218B},
    {0x2190, 0x2429},
    {0x2440, 0x244A},
    {0x2460, 0x27FF},
    {0x2900, 0x2B73},
    {0x2B76, 0x2B95},
    {0x2B97, 0x2BFF},
    {0x2E00, 0x2E16},
    {0x2E18, 0x2E2F},
    {0x2E32, 0x2E3B},
    {0x2E3D, 0x2E40},
    {0x2E42, 0x2E42},
    {0x2E44, 0x2E5D},
    {0x3000, 0x3000},
    {0x3004, 0x3004},
    {0x3012, 0x3012},
    {0x3020, 0x3020},
    {0x3036, 0x3036},
    {0x3248, 0x325F},
    {0x327F, 0x327F},
    {0x32B1, 0x32BF},
    {0x32CC, 0x32CF},
    {0x3371, 0x337A},
    {0x3380, 0x33DF},
    {0x33FF, 0x33FF},
    {0x4DC0, 0x4DFF},
    {0xA708, 0xA721},
    {0xA788, 0xA78A},
    {0xAB5B, 0xAB5B},
    {0xAB6A, 0xAB6B},
    {0xFE10, 0xFE19},
    {0xFE30, 0xFE44},
    {0xFE47, 0xFE52},
    {0xFE54, 0xFE66},
    {0xFE68, 0xFE6B},
    {0xFEFF, 0xFEFF},
    {0xFF01, 0xFF20},
    {0xFF3B, 0xFF40},
    {0xFF5B, 0xFF60},
    {0xFFE0, 0xFFE6},
    {0xFFE8, 0xFFEE},
    {0xFFF9, 0xFFFD},
    {0x10190, 0x1019C},
    {0x101D0, 0x101FC},
    {0x1CC00, 0x1CCF9},
    {0x1CD00, 0x1CEB3},
    {0x1CF50, 0x1CFC3},
    {0x1D000, 0x1D0F5},
    {0x1D100, 0x1D126},
    {0x1D129, 0x1D166},
    {0x1D16A, 0x1D17A},
    {0x1D183, 0x1D184},
    {0x1D18C, 0x1D1A9},
    {0x1D1AE, 0x1D1EA},
    {0x1D2C0, 0x1D2D3},
    {0x1D2E0, 0x1D2F3},
    {0x1D300, 0x1D356},
    {0x1D372, 0x1D378},
    {0x1D400, 0x1D454},
    {0x1D456, 0x1D49C},
    {0x1D49E, 0x1D49F},
    {0x1D4A2, 0x1D4A2},
    {0x1D4A5, 0x1D4A6},
    {0x1D4A9, 0x1D4AC},
    {0x1D4AE, 0x1D4B9},
    {0x1D4BB, 0x1D4BB},
    {0x1D4BD, 0x1D4C3},
    {0x1D4C5, 0x1D505},
    {0x1D507, 0x1D50A},
    {0x1D50D, 0x1D514},
    {0x1D516, 0x1D51C},
    {0x1D51E, 0x1D539},
    {0x1D53B, 0x1D53E},
    {0x1D540, 0x1D544},
    {0x1D546, 0x1D546},
    {0x1D54A, 0x1D550},
    {0x1D552, 0x1D6A5},
    {0x1D6A8, 0x1D7CB},
    {0x1D7CE, 0x1D7FF},
    {0x1EC71, 0x1ECB4},
    {0x1ED01, 0x1ED3D},
    {0x1F000, 0x1F02B},
    {0x1F030, 0x1F093},
    {0x1F0A0, 0x1F0AE},
    {0x1F0B1, 0x1F0BF},
    {0x1F0C1, 0x1F0CF},
    {0x1F0D1, 0x1F0F5},
    {0x1F100, 0x1F1AD},
    {0x1F1E6, 0x1F1FF},
    {0x1F201, 0x1F202},
    {0x1F210, 0x1F23B},
    {0x1F240, 0x1F248},
    {0x1F260, 0x1F265},
    {0x1F300, 0x1F6D7},
    {0x1F6DC, 0x1F6EC},
    {0x1F6F0, 0x1F6FC},
    {0x1F700, 0x1F776},
    {0x1F77B, 0x1F7D9},
    {0x1F7E0, 0x1F7EB},
    {0x1F7F0, 0x1F7F0},
    {0x1F800, 0x1F80B},
    {0x1F810, 0x1F847},
    {0x1F850, 0x1F859},
    {0x1F860, 0x1F887},
    {0x1F890, 0x1F8AD},
    {0x1F8B0, 0x1F8BB},
    {0x1F8C0, 0x1F8C1},
    {0x1F900, 0x1FA53},
    {0x1FA60, 0x1FA6D},
    {0x1FA70, 0x1FA7C},
    {0x1FA80, 0x1FA89},
    {0x1FA8F, 0x1FAC6},
    {0x1FACE, 0x1FADC},
    {0x1FADF, 0x1FAE9},
    {0x1FAF0, 0x1FAF8},
    {0x1FB00, 0x1FB92},
    {0x1FB94, 0x1FBF9},
    {0xE0001, 0xE0001},
    {0xE0020, 0xE007F},
  };

  //! \brief `\p{scx=Coptic}` — 10 ranges, 173 code points.
  inline constexpr code_range scx_Coptic_ranges[] {
    {0x00B7, 0x00B7},
    {0x0300, 0x0300},
    {0x0304, 0x0305},
    {0x0307, 0x0307},
    {0x0374, 0x0375},
    {0x03E2, 0x03EF},
    {0x2C80, 0x2CF3},
    {0x2CF9, 0x2CFF},
    {0x2E17, 0x2E17},
    {0x102E0, 0x102FB},
  };

  //! \brief `\p{scx=Cuneiform}` — 4 ranges, 1234 code points.
  inline constexpr code_range scx_Cuneiform_ranges[] {
    {0x12000, 0x12399},
    {0x12400, 0x1246E},
    {0x12470, 0x12474},
    {0x12480, 0x12543},
  };

  //! \brief `\p{scx=Cypriot}` — 9 ranges, 112 code points.
  inline constexpr code_range scx_Cypriot_ranges[] {
    {0x10100, 0x10102},
    {0x10107, 0x10133},
    {0x10137, 0x1013F},
    {0x10800, 0x10805},
    {0x10808, 0x10808},
    {0x1080A, 0x10835},
    {0x10837, 0x10838},
    {0x1083C, 0x1083C},
    {0x1083F, 0x1083F},
  };

  //! \brief `\p{scx=Cypro_Minoan}` — 2 ranges, 101 code points.
  inline constexpr code_range scx_Cypro_Minoan_ranges[] {
    {0x10100, 0x10101},
    {0x12F90, 0x12FF2},
  };

  //! \brief `\p{scx=Cyrillic}` — 18 ranges, 521 code points.
  inline constexpr code_range scx_Cyrillic_ranges[] {
    {0x02BC, 0x02BC},
    {0x0300, 0x0302},
    {0x0304, 0x0304},
    {0x0306, 0x0306},
    {0x0308, 0x0308},
    {0x030B, 0x030B},
    {0x0311, 0x0311},
    {0x0400, 0x052F},
    {0x1C80, 0x1C8A},
    {0x1D2B, 0x1D2B},
    {0x1D78, 0x1D78},
    {0x1DF8, 0x1DF8},
    {0x2DE0, 0x2DFF},
    {0x2E43, 0x2E43},
    {0xA640, 0xA69F},
    {0xFE2E, 0xFE2F},
    {0x1E030, 0x1E06D},
    {0x1E08F, 0x1E08F},
  };

  //! \brief `\p{scx=Deseret}` — 1 ranges, 80 code points.
  inline constexpr code_range scx_Deseret_ranges[] {
    {0x10400, 0x1044F},
  };

  //! \brief `\p{scx=Devanagari}` — 9 ranges, 221 code points.
  inline constexpr code_range scx_Devanagari_ranges[] {
    {0x02BC, 0x02BC},
    {0x0900, 0x0952},
    {0x0955, 0x097F},
    {0x1CD0, 0x1CF6},
    {0x1CF8, 0x1CF9},
    {0x20F0, 0x20F0},
    {0xA830, 0xA839},
    {0xA8E0, 0xA8FF},
    {0x11B00, 0x11B09},
  };

  //! \brief `\p{scx=Dives_Akuru}` — 8 ranges, 72 code points.
  inline constexpr code_range scx_Dives_Akuru_ranges[] {
    {0x11900, 0x11906},
    {0x11909, 0x11909},
    {0x1190C, 0x11913},
    {0x11915, 0x11916},
    {0x11918, 0x11935},
    {0x11937, 0x11938},
    {0x1193B, 0x11946},
    {0x11950, 0x11959},
  };

  //! \brief `\p{scx=Dogra}` — 3 ranges, 82 code points.
  inline constexpr code_range scx_Dogra_ranges[] {
    {0x0964, 0x096F},
    {0xA830, 0xA839},
    {0x11800, 0x1183B},
  };

  //! \brief `\p{scx=Duployan}` — 10 ranges, 154 code points.
  inline constexpr code_range scx_Duployan_ranges[] {
    {0x00B7, 0x00B7},
    {0x0307, 0x0308},
    {0x030A, 0x030A},
    {0x0323, 0x0324},
    {0x2E3C, 0x2E3C},
    {0x1BC00, 0x1BC6A},
    {0x1BC70, 0x1BC7C},
    {0x1BC80, 0x1BC88},
    {0x1BC90, 0x1BC99},
    {0x1BC9C, 0x1BCA3},
  };

  //! \brief `\p{scx=Egyptian_Hieroglyphs}` — 2 ranges, 5105 code points.
  inline constexpr code_range scx_Egyptian_Hieroglyphs_ranges[] {
    {0x13000, 0x13455},
    {0x13460, 0x143FA},
  };

  //! \brief `\p{scx=Elbasan}` — 3 ranges, 42 code points.
  inline constexpr code_range scx_Elbasan_ranges[] {
    {0x00B7, 0x00B7},
    {0x0305, 0x0305},
    {0x10500, 0x10527},
  };

  //! \brief `\p{scx=Elymaic}` — 1 ranges, 23 code points.
  inline constexpr code_range scx_Elymaic_ranges[] {
    {0x10FE0, 0x10FF6},
  };

  //! \brief `\p{scx=Ethiopic}` — 37 ranges, 524 code points.
  inline constexpr code_range scx_Ethiopic_ranges[] {
    {0x030E, 0x030E},
    {0x1200, 0x1248},
    {0x124A, 0x124D},
    {0x1250, 0x1256},
    {0x1258, 0x1258},
    {0x125A, 0x125D},
    {0x1260, 0x1288},
    {0x128A, 0x128D},
    {0x1290, 0x12B0},
    {0x12B2, 0x12B5},
    {0x12B8, 0x12BE},
    {0x12C0, 0x12C0},
    {0x12C2, 0x12C5},
    {0x12C8, 0x12D6},
    {0x12D8, 0x1310},
    {0x1312, 0x1315},
    {0x1318, 0x135A},
    {0x135D, 0x137C},
    {0x1380, 0x1399},
    {0x2D80, 0x2D96},
    {0x2DA0, 0x2DA6},
    {0x2DA8, 0x2DAE},
    {0x2DB0, 0x2DB6},
    {0x2DB8, 0x2DBE},
    {0x2DC0, 0x2DC6},
    {0x2DC8, 0x2DCE},
    {0x2DD0, 0x2DD6},
    {0x2DD8, 0x2DDE},
    {0xAB01, 0xAB06},
    {0xAB09, 0xAB0E},
    {0xAB11, 0xAB16},
    {0xAB20, 0xAB26},
    {0xAB28, 0xAB2E},
    {0x1E7E0, 0x1E7E6},
    {0x1E7E8, 0x1E7EB},
    {0x1E7ED, 0x1E7EE},
    {0x1E7F0, 0x1E7FE},
  };

  //! \brief `\p{scx=Garay}` — 6 ranges, 72 code points.
  inline constexpr code_range scx_Garay_ranges[] {
    {0x060C, 0x060C},
    {0x061B, 0x061B},
    {0x061F, 0x061F},
    {0x10D40, 0x10D65},
    {0x10D69, 0x10D85},
    {0x10D8E, 0x10D8F},
  };

  //! \brief `\p{scx=Georgian}` — 13 ranges, 178 code points.
  inline constexpr code_range scx_Georgian_ranges[] {
    {0x00B7, 0x00B7},
    {0x0589, 0x0589},
    {0x10A0, 0x10C5},
    {0x10C7, 0x10C7},
    {0x10CD, 0x10CD},
    {0x10D0, 0x10FF},
    {0x1C90, 0x1CBA},
    {0x1CBD, 0x1CBF},
    {0x205A, 0x205A},
    {0x2D00, 0x2D25},
    {0x2D27, 0x2D27},
    {0x2D2D, 0x2D2D},
    {0x2E31, 0x2E31},
  };

  //! \brief `\p{scx=Glagolitic}` — 16 ranges, 144 code points.
  inline constexpr code_range scx_Glagolitic_ranges[] {
    {0x00B7, 0x00B7},
    {0x0303, 0x0303},
    {0x0305, 0x0305},
    {0x0484, 0x0484},
    {0x0487, 0x0487},
    {0x0589, 0x0589},
    {0x10FB, 0x10FB},
    {0x205A, 0x205A},
    {0x2C00, 0x2C5F},
    {0x2E43, 0x2E43},
    {0xA66F, 0xA66F},
    {0x1E000, 0x1E006},
    {0x1E008, 0x1E018},
    {0x1E01B, 0x1E021},
    {0x1E023, 0x1E024},
    {0x1E026, 0x1E02A},
  };

  //! \brief `\p{scx=Gothic}` — 5 ranges, 32 code points.
  inline constexpr code_range scx_Gothic_ranges[] {
    {0x00B7, 0x00B7},
    {0x0304, 0x0305},
    {0x0308, 0x0308},
    {0x0331, 0x0331},
    {0x10330, 0x1034A},
  };

  //! \brief `\p{scx=Grantha}` — 25 ranges, 116 code points.
  inline constexpr code_range scx_Grantha_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0BE6, 0x0BF3},
    {0x1CD0, 0x1CD0},
    {0x1CD2, 0x1CD3},
    {0x1CF2, 0x1CF4},
    {0x1CF8, 0x1CF9},
    {0x20F0, 0x20F0},
    {0x11300, 0x11303},
    {0x11305, 0x1130C},
    {0x1130F, 0x11310},
    {0x11313, 0x11328},
    {0x1132A, 0x11330},
    {0x11332, 0x11333},
    {0x11335, 0x11339},
    {0x1133B, 0x11344},
    {0x11347, 0x11348},
    {0x1134B, 0x1134D},
    {0x11350, 0x11350},
    {0x11357, 0x11357},
    {0x1135D, 0x11363},
    {0x11366, 0x1136C},
    {0x11370, 0x11374},
    {0x11FD0, 0x11FD1},
    {0x11FD3, 0x11FD3},
  };

  //! \brief `\p{scx=Greek}` — 44 ranges, 531 code points.
  inline constexpr code_range scx_Greek_ranges[] {
    {0x00B7, 0x00B7},
    {0x0300, 0x0301},
    {0x0304, 0x0304},
    {0x0306, 0x0306},
    {0x0308, 0x0308},
    {0x0313, 0x0313},
    {0x0342, 0x0342},
    {0x0345, 0x0345},
    {0x0370, 0x0377},
    {0x037A, 0x037D},
    {0x037F, 0x037F},
    {0x0384, 0x0384},
    {0x0386, 0x0386},
    {0x0388, 0x038A},
    {0x038C, 0x038C},
    {0x038E, 0x03A1},
    {0x03A3, 0x03E1},
    {0x03F0, 0x03FF},
    {0x1D26, 0x1D2A},
    {0x1D5D, 0x1D61},
    {0x1D66, 0x1D6A},
    {0x1DBF, 0x1DC1},
    {0x1F00, 0x1F15},
    {0x1F18, 0x1F1D},
    {0x1F20, 0x1F45},
    {0x1F48, 0x1F4D},
    {0x1F50, 0x1F57},
    {0x1F59, 0x1F59},
    {0x1F5B, 0x1F5B},
    {0x1F5D, 0x1F5D},
    {0x1F5F, 0x1F7D},
    {0x1F80, 0x1FB4},
    {0x1FB6, 0x1FC4},
    {0x1FC6, 0x1FD3},
    {0x1FD6, 0x1FDB},
    {0x1FDD, 0x1FEF},
    {0x1FF2, 0x1FF4},
    {0x1FF6, 0x1FFE},
    {0x205D, 0x205D},
    {0x2126, 0x2126},
    {0xAB65, 0xAB65},
    {0x10140, 0x1018E},
    {0x101A0, 0x101A0},
    {0x1D200, 0x1D245},
  };

  //! \brief `\p{scx=Gujarati}` — 17 ranges, 105 code points.
  inline constexpr code_range scx_Gujarati_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0A81, 0x0A83},
    {0x0A85, 0x0A8D},
    {0x0A8F, 0x0A91},
    {0x0A93, 0x0AA8},
    {0x0AAA, 0x0AB0},
    {0x0AB2, 0x0AB3},
    {0x0AB5, 0x0AB9},
    {0x0ABC, 0x0AC5},
    {0x0AC7, 0x0AC9},
    {0x0ACB, 0x0ACD},
    {0x0AD0, 0x0AD0},
    {0x0AE0, 0x0AE3},
    {0x0AE6, 0x0AF1},
    {0x0AF9, 0x0AFF},
    {0xA830, 0xA839},
  };

  //! \brief `\p{scx=Gunjala_Gondi}` — 8 ranges, 66 code points.
  inline constexpr code_range scx_Gunjala_Gondi_ranges[] {
    {0x00B7, 0x00B7},
    {0x0964, 0x0965},
    {0x11D60, 0x11D65},
    {0x11D67, 0x11D68},
    {0x11D6A, 0x11D8E},
    {0x11D90, 0x11D91},
    {0x11D93, 0x11D98},
    {0x11DA0, 0x11DA9},
  };

  //! \brief `\p{scx=Gurmukhi}` — 19 ranges, 94 code points.
  inline constexpr code_range scx_Gurmukhi_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0A01, 0x0A03},
    {0x0A05, 0x0A0A},
    {0x0A0F, 0x0A10},
    {0x0A13, 0x0A28},
    {0x0A2A, 0x0A30},
    {0x0A32, 0x0A33},
    {0x0A35, 0x0A36},
    {0x0A38, 0x0A39},
    {0x0A3C, 0x0A3C},
    {0x0A3E, 0x0A42},
    {0x0A47, 0x0A48},
    {0x0A4B, 0x0A4D},
    {0x0A51, 0x0A51},
    {0x0A59, 0x0A5C},
    {0x0A5E, 0x0A5E},
    {0x0A66, 0x0A76},
    {0xA830, 0xA839},
  };

  //! \brief `\p{scx=Gurung_Khema}` — 2 ranges, 59 code points.
  inline constexpr code_range scx_Gurung_Khema_ranges[] {
    {0x0965, 0x0965},
    {0x16100, 0x16139},
  };

  //! \brief `\p{scx=Han}` — 42 ranges, 99338 code points.
  inline constexpr code_range scx_Han_ranges[] {
    {0x00B7, 0x00B7},
    {0x2E80, 0x2E99},
    {0x2E9B, 0x2EF3},
    {0x2F00, 0x2FD5},
    {0x2FF0, 0x2FFF},
    {0x3001, 0x3003},
    {0x3005, 0x3011},
    {0x3013, 0x301F},
    {0x3021, 0x302D},
    {0x3030, 0x3030},
    {0x3037, 0x303F},
    {0x30FB, 0x30FB},
    {0x3190, 0x319F},
    {0x31C0, 0x31E5},
    {0x31EF, 0x31EF},
    {0x3220, 0x3247},
    {0x3280, 0x32B0},
    {0x32C0, 0x32CB},
    {0x32FF, 0x32FF},
    {0x3358, 0x3370},
    {0x337B, 0x337F},
    {0x33E0, 0x33FE},
    {0x3400, 0x4DBF},
    {0x4E00, 0x9FFF},
    {0xA700, 0xA707},
    {0xF900, 0xFA6D},
    {0xFA70, 0xFAD9},
    {0xFE45, 0xFE46},
    {0xFF61, 0xFF65},
    {0x16FE2, 0x16FE3},
    {0x16FF0, 0x16FF1},
    {0x1D360, 0x1D371},
    {0x1F250, 0x1F251},
    {0x20000, 0x2A6DF},
    {0x2A700, 0x2B739},
    {0x2B740, 0x2B81D},
    {0x2B820, 0x2CEA1},
    {0x2CEB0, 0x2EBE0},
    {0x2EBF0, 0x2EE5D},
    {0x2F800, 0x2FA1D},
    {0x30000, 0x3134A},
    {0x31350, 0x323AF},
  };

  //! \brief `\p{scx=Hangul}` — 21 ranges, 11775 code points.
  inline constexpr code_range scx_Hangul_ranges[] {
    {0x1100, 0x11FF},
    {0x3001, 0x3003},
    {0x3008, 0x3011},
    {0x3013, 0x301F},
    {0x302E, 0x3030},
    {0x3037, 0x3037},
    {0x30FB, 0x30FB},
    {0x3131, 0x318E},
    {0x3200, 0x321E},
    {0x3260, 0x327E},
    {0xA960, 0xA97C},
    {0xAC00, 0xD7A3},
    {0xD7B0, 0xD7C6},
    {0xD7CB, 0xD7FB},
    {0xFE45, 0xFE46},
    {0xFF61, 0xFF65},
    {0xFFA0, 0xFFBE},
    {0xFFC2, 0xFFC7},
    {0xFFCA, 0xFFCF},
    {0xFFD2, 0xFFD7},
    {0xFFDA, 0xFFDC},
  };

  //! \brief `\p{scx=Hanifi_Rohingya}` — 7 ranges, 55 code points.
  inline constexpr code_range scx_Hanifi_Rohingya_ranges[] {
    {0x060C, 0x060C},
    {0x061B, 0x061B},
    {0x061F, 0x061F},
    {0x0640, 0x0640},
    {0x06D4, 0x06D4},
    {0x10D00, 0x10D27},
    {0x10D30, 0x10D39},
  };

  //! \brief `\p{scx=Hanunoo}` — 1 ranges, 23 code points.
  inline constexpr code_range scx_Hanunoo_ranges[] {
    {0x1720, 0x1736},
  };

  //! \brief `\p{scx=Hatran}` — 3 ranges, 26 code points.
  inline constexpr code_range scx_Hatran_ranges[] {
    {0x108E0, 0x108F2},
    {0x108F4, 0x108F5},
    {0x108FB, 0x108FF},
  };

  //! \brief `\p{scx=Hebrew}` — 10 ranges, 136 code points.
  inline constexpr code_range scx_Hebrew_ranges[] {
    {0x0307, 0x0308},
    {0x0591, 0x05C7},
    {0x05D0, 0x05EA},
    {0x05EF, 0x05F4},
    {0xFB1D, 0xFB36},
    {0xFB38, 0xFB3C},
    {0xFB3E, 0xFB3E},
    {0xFB40, 0xFB41},
    {0xFB43, 0xFB44},
    {0xFB46, 0xFB4F},
  };

  //! \brief `\p{scx=Hiragana}` — 17 ranges, 433 code points.
  inline constexpr code_range scx_Hiragana_ranges[] {
    {0x3001, 0x3003},
    {0x3008, 0x3011},
    {0x3013, 0x301F},
    {0x3030, 0x3035},
    {0x3037, 0x3037},
    {0x303C, 0x303D},
    {0x3041, 0x3096},
    {0x3099, 0x30A0},
    {0x30FB, 0x30FC},
    {0xFE45, 0xFE46},
    {0xFF61, 0xFF65},
    {0xFF70, 0xFF70},
    {0xFF9E, 0xFF9F},
    {0x1B001, 0x1B11F},
    {0x1B132, 0x1B132},
    {0x1B150, 0x1B152},
    {0x1F200, 0x1F200},
  };

  //! \brief `\p{scx=Imperial_Aramaic}` — 2 ranges, 31 code points.
  inline constexpr code_range scx_Imperial_Aramaic_ranges[] {
    {0x10840, 0x10855},
    {0x10857, 0x1085F},
  };

  //! \brief `\p{scx=Inherited}` — 28 ranges, 558 code points.
  inline constexpr code_range scx_Inherited_ranges[] {
    {0x030F, 0x030F},
    {0x0312, 0x0312},
    {0x0314, 0x031F},
    {0x0321, 0x0322},
    {0x0326, 0x032C},
    {0x032F, 0x032F},
    {0x0332, 0x0341},
    {0x0343, 0x0344},
    {0x0346, 0x0357},
    {0x0359, 0x035D},
    {0x035F, 0x0362},
    {0x0953, 0x0954},
    {0x1AB0, 0x1ACE},
    {0x1DC2, 0x1DF7},
    {0x1DF9, 0x1DF9},
    {0x1DFB, 0x1DFF},
    {0x200C, 0x200D},
    {0x20D0, 0x20EF},
    {0xFE00, 0xFE0F},
    {0xFE20, 0xFE2D},
    {0x101FD, 0x101FD},
    {0x1CF00, 0x1CF2D},
    {0x1CF30, 0x1CF46},
    {0x1D167, 0x1D169},
    {0x1D17B, 0x1D182},
    {0x1D185, 0x1D18B},
    {0x1D1AA, 0x1D1AD},
    {0xE0100, 0xE01EF},
  };

  //! \brief `\p{scx=Inscriptional_Pahlavi}` — 2 ranges, 27 code points.
  inline constexpr code_range scx_Inscriptional_Pahlavi_ranges[] {
    {0x10B60, 0x10B72},
    {0x10B78, 0x10B7F},
  };

  //! \brief `\p{scx=Inscriptional_Parthian}` — 2 ranges, 30 code points.
  inline constexpr code_range scx_Inscriptional_Parthian_ranges[] {
    {0x10B40, 0x10B55},
    {0x10B58, 0x10B5F},
  };

  //! \brief `\p{scx=Javanese}` — 3 ranges, 91 code points.
  inline constexpr code_range scx_Javanese_ranges[] {
    {0xA980, 0xA9CD},
    {0xA9CF, 0xA9D9},
    {0xA9DE, 0xA9DF},
  };

  //! \brief `\p{scx=Kaithi}` — 5 ranges, 89 code points.
  inline constexpr code_range scx_Kaithi_ranges[] {
    {0x0966, 0x096F},
    {0x2E31, 0x2E31},
    {0xA830, 0xA839},
    {0x11080, 0x110C2},
    {0x110CD, 0x110CD},
  };

  //! \brief `\p{scx=Kannada}` — 21 ranges, 107 code points.
  inline constexpr code_range scx_Kannada_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0C80, 0x0C8C},
    {0x0C8E, 0x0C90},
    {0x0C92, 0x0CA8},
    {0x0CAA, 0x0CB3},
    {0x0CB5, 0x0CB9},
    {0x0CBC, 0x0CC4},
    {0x0CC6, 0x0CC8},
    {0x0CCA, 0x0CCD},
    {0x0CD5, 0x0CD6},
    {0x0CDD, 0x0CDE},
    {0x0CE0, 0x0CE3},
    {0x0CE6, 0x0CEF},
    {0x0CF1, 0x0CF3},
    {0x1CD0, 0x1CD0},
    {0x1CD2, 0x1CD3},
    {0x1CDA, 0x1CDA},
    {0x1CF2, 0x1CF2},
    {0x1CF4, 0x1CF4},
    {0xA830, 0xA835},
  };

  //! \brief `\p{scx=Katakana}` — 22 ranges, 375 code points.
  inline constexpr code_range scx_Katakana_ranges[] {
    {0x0305, 0x0305},
    {0x0323, 0x0323},
    {0x3001, 0x3003},
    {0x3008, 0x3011},
    {0x3013, 0x301F},
    {0x3030, 0x3035},
    {0x3037, 0x3037},
    {0x303C, 0x303D},
    {0x3099, 0x309C},
    {0x30A0, 0x30FF},
    {0x31F0, 0x31FF},
    {0x32D0, 0x32FE},
    {0x3300, 0x3357},
    {0xFE45, 0xFE46},
    {0xFF61, 0xFF9F},
    {0x1AFF0, 0x1AFF3},
    {0x1AFF5, 0x1AFFB},
    {0x1AFFD, 0x1AFFE},
    {0x1B000, 0x1B000},
    {0x1B120, 0x1B122},
    {0x1B155, 0x1B155},
    {0x1B164, 0x1B167},
  };

  //! \brief `\p{scx=Kawi}` — 3 ranges, 87 code points.
  inline constexpr code_range scx_Kawi_ranges[] {
    {0x11F00, 0x11F10},
    {0x11F12, 0x11F3A},
    {0x11F3E, 0x11F5A},
  };

  //! \brief `\p{scx=Kayah_Li}` — 1 ranges, 48 code points.
  inline constexpr code_range scx_Kayah_Li_ranges[] {
    {0xA900, 0xA92F},
  };

  //! \brief `\p{scx=Kharoshthi}` — 8 ranges, 68 code points.
  inline constexpr code_range scx_Kharoshthi_ranges[] {
    {0x10A00, 0x10A03},
    {0x10A05, 0x10A06},
    {0x10A0C, 0x10A13},
    {0x10A15, 0x10A17},
    {0x10A19, 0x10A35},
    {0x10A38, 0x10A3A},
    {0x10A3F, 0x10A48},
    {0x10A50, 0x10A58},
  };

  //! \brief `\p{scx=Khitan_Small_Script}` — 3 ranges, 472 code points.
  inline constexpr code_range scx_Khitan_Small_Script_ranges[] {
    {0x16FE4, 0x16FE4},
    {0x18B00, 0x18CD5},
    {0x18CFF, 0x18CFF},
  };

  //! \brief `\p{scx=Khmer}` — 4 ranges, 146 code points.
  inline constexpr code_range scx_Khmer_ranges[] {
    {0x1780, 0x17DD},
    {0x17E0, 0x17E9},
    {0x17F0, 0x17F9},
    {0x19E0, 0x19FF},
  };

  //! \brief `\p{scx=Khojki}` — 4 ranges, 85 code points.
  inline constexpr code_range scx_Khojki_ranges[] {
    {0x0AE6, 0x0AEF},
    {0xA830, 0xA839},
    {0x11200, 0x11211},
    {0x11213, 0x11241},
  };

  //! \brief `\p{scx=Khudawadi}` — 4 ranges, 81 code points.
  inline constexpr code_range scx_Khudawadi_ranges[] {
    {0x0964, 0x0965},
    {0xA830, 0xA839},
    {0x112B0, 0x112EA},
    {0x112F0, 0x112F9},
  };

  //! \brief `\p{scx=Kirat_Rai}` — 1 ranges, 58 code points.
  inline constexpr code_range scx_Kirat_Rai_ranges[] {
    {0x16D40, 0x16D79},
  };

  //! \brief `\p{scx=Lao}` — 11 ranges, 83 code points.
  inline constexpr code_range scx_Lao_ranges[] {
    {0x0E81, 0x0E82},
    {0x0E84, 0x0E84},
    {0x0E86, 0x0E8A},
    {0x0E8C, 0x0EA3},
    {0x0EA5, 0x0EA5},
    {0x0EA7, 0x0EBD},
    {0x0EC0, 0x0EC4},
    {0x0EC6, 0x0EC6},
    {0x0EC8, 0x0ECE},
    {0x0ED0, 0x0ED9},
    {0x0EDC, 0x0EDF},
  };

  //! \brief `\p{scx=Latin}` — 65 ranges, 1555 code points.
  inline constexpr code_range scx_Latin_ranges[] {
    {0x0041, 0x005A},
    {0x0061, 0x007A},
    {0x00AA, 0x00AA},
    {0x00B7, 0x00B7},
    {0x00BA, 0x00BA},
    {0x00C0, 0x00D6},
    {0x00D8, 0x00F6},
    {0x00F8, 0x02B8},
    {0x02BC, 0x02BC},
    {0x02C7, 0x02C7},
    {0x02C9, 0x02CB},
    {0x02CD, 0x02CD},
    {0x02D7, 0x02D7},
    {0x02D9, 0x02D9},
    {0x02E0, 0x02E4},
    {0x0300, 0x030E},
    {0x0310, 0x0311},
    {0x0313, 0x0313},
    {0x0320, 0x0320},
    {0x0323, 0x0325},
    {0x032D, 0x032E},
    {0x0330, 0x0331},
    {0x0358, 0x0358},
    {0x035E, 0x035E},
    {0x0363, 0x036F},
    {0x0485, 0x0486},
    {0x0951, 0x0952},
    {0x10FB, 0x10FB},
    {0x1D00, 0x1D25},
    {0x1D2C, 0x1D5C},
    {0x1D62, 0x1D65},
    {0x1D6B, 0x1D77},
    {0x1D79, 0x1DBE},
    {0x1DF8, 0x1DF8},
    {0x1E00, 0x1EFF},
    {0x202F, 0x202F},
    {0x2071, 0x2071},
    {0x207F, 0x207F},
    {0x2090, 0x209C},
    {0x20F0, 0x20F0},
    {0x212A, 0x212B},
    {0x2132, 0x2132},
    {0x214E, 0x214E},
    {0x2160, 0x2188},
    {0x2C60, 0x2C7F},
    {0x2E17, 0x2E17},
    {0xA700, 0xA707},
    {0xA722, 0xA787},
    {0xA78B, 0xA7CD},
    {0xA7D0, 0xA7D1},
    {0xA7D3, 0xA7D3},
    {0xA7D5, 0xA7DC},
    {0xA7F2, 0xA7FF},
    {0xA92E, 0xA92E},
    {0xAB30, 0xAB5A},
    {0xAB5C, 0xAB64},
    {0xAB66, 0xAB69},
    {0xFB00, 0xFB06},
    {0xFF21, 0xFF3A},
    {0xFF41, 0xFF5A},
    {0x10780, 0x10785},
    {0x10787, 0x107B0},
    {0x107B2, 0x107BA},
    {0x1DF00, 0x1DF1E},
    {0x1DF25, 0x1DF2A},
  };

  //! \brief `\p{scx=Lepcha}` — 3 ranges, 74 code points.
  inline constexpr code_range scx_Lepcha_ranges[] {
    {0x1C00, 0x1C37},
    {0x1C3B, 0x1C49},
    {0x1C4D, 0x1C4F},
  };

  //! \brief `\p{scx=Limbu}` — 6 ranges, 69 code points.
  inline constexpr code_range scx_Limbu_ranges[] {
    {0x0965, 0x0965},
    {0x1900, 0x191E},
    {0x1920, 0x192B},
    {0x1930, 0x193B},
    {0x1940, 0x1940},
    {0x1944, 0x194F},
  };

  //! \brief `\p{scx=Linear_A}` — 4 ranges, 386 code points.
  inline constexpr code_range scx_Linear_A_ranges[] {
    {0x10107, 0x10133},
    {0x10600, 0x10736},
    {0x10740, 0x10755},
    {0x10760, 0x10767},
  };

  //! \brief `\p{scx=Linear_B}` — 10 ranges, 268 code points.
  inline constexpr code_range scx_Linear_B_ranges[] {
    {0x10000, 0x1000B},
    {0x1000D, 0x10026},
    {0x10028, 0x1003A},
    {0x1003C, 0x1003D},
    {0x1003F, 0x1004D},
    {0x10050, 0x1005D},
    {0x10080, 0x100FA},
    {0x10100, 0x10102},
    {0x10107, 0x10133},
    {0x10137, 0x1013F},
  };

  //! \brief `\p{scx=Lisu}` — 5 ranges, 53 code points.
  inline constexpr code_range scx_Lisu_ranges[] {
    {0x02BC, 0x02BC},
    {0x02CD, 0x02CD},
    {0x300A, 0x300B},
    {0xA4D0, 0xA4FF},
    {0x11FB0, 0x11FB0},
  };

  //! \brief `\p{scx=Lycian}` — 2 ranges, 30 code points.
  inline constexpr code_range scx_Lycian_ranges[] {
    {0x205A, 0x205A},
    {0x10280, 0x1029C},
  };

  //! \brief `\p{scx=Lydian}` — 4 ranges, 29 code points.
  inline constexpr code_range scx_Lydian_ranges[] {
    {0x00B7, 0x00B7},
    {0x2E31, 0x2E31},
    {0x10920, 0x10939},
    {0x1093F, 0x1093F},
  };

  //! \brief `\p{scx=Mahajani}` — 4 ranges, 62 code points.
  inline constexpr code_range scx_Mahajani_ranges[] {
    {0x00B7, 0x00B7},
    {0x0964, 0x096F},
    {0xA830, 0xA839},
    {0x11150, 0x11176},
  };

  //! \brief `\p{scx=Makasar}` — 1 ranges, 25 code points.
  inline constexpr code_range scx_Makasar_ranges[] {
    {0x11EE0, 0x11EF8},
  };

  //! \brief `\p{scx=Malayalam}` — 12 ranges, 127 code points.
  inline constexpr code_range scx_Malayalam_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0D00, 0x0D0C},
    {0x0D0E, 0x0D10},
    {0x0D12, 0x0D44},
    {0x0D46, 0x0D48},
    {0x0D4A, 0x0D4F},
    {0x0D54, 0x0D63},
    {0x0D66, 0x0D7F},
    {0x1CDA, 0x1CDA},
    {0x1CF2, 0x1CF2},
    {0xA830, 0xA832},
  };

  //! \brief `\p{scx=Mandaic}` — 3 ranges, 30 code points.
  inline constexpr code_range scx_Mandaic_ranges[] {
    {0x0640, 0x0640},
    {0x0840, 0x085B},
    {0x085E, 0x085E},
  };

  //! \brief `\p{scx=Manichaean}` — 3 ranges, 52 code points.
  inline constexpr code_range scx_Manichaean_ranges[] {
    {0x0640, 0x0640},
    {0x10AC0, 0x10AE6},
    {0x10AEB, 0x10AF6},
  };

  //! \brief `\p{scx=Marchen}` — 3 ranges, 68 code points.
  inline constexpr code_range scx_Marchen_ranges[] {
    {0x11C70, 0x11C8F},
    {0x11C92, 0x11CA7},
    {0x11CA9, 0x11CB6},
  };

  //! \brief `\p{scx=Masaram_Gondi}` — 8 ranges, 77 code points.
  inline constexpr code_range scx_Masaram_Gondi_ranges[] {
    {0x0964, 0x0965},
    {0x11D00, 0x11D06},
    {0x11D08, 0x11D09},
    {0x11D0B, 0x11D36},
    {0x11D3A, 0x11D3A},
    {0x11D3C, 0x11D3D},
    {0x11D3F, 0x11D47},
    {0x11D50, 0x11D59},
  };

  //! \brief `\p{scx=Medefaidrin}` — 1 ranges, 91 code points.
  inline constexpr code_range scx_Medefaidrin_ranges[] {
    {0x16E40, 0x16E9A},
  };

  //! \brief `\p{scx=Meetei_Mayek}` — 3 ranges, 79 code points.
  inline constexpr code_range scx_Meetei_Mayek_ranges[] {
    {0xAAE0, 0xAAF6},
    {0xABC0, 0xABED},
    {0xABF0, 0xABF9},
  };

  //! \brief `\p{scx=Mende_Kikakui}` — 2 ranges, 213 code points.
  inline constexpr code_range scx_Mende_Kikakui_ranges[] {
    {0x1E800, 0x1E8C4},
    {0x1E8C7, 0x1E8D6},
  };

  //! \brief `\p{scx=Meroitic_Cursive}` — 3 ranges, 90 code points.
  inline constexpr code_range scx_Meroitic_Cursive_ranges[] {
    {0x109A0, 0x109B7},
    {0x109BC, 0x109CF},
    {0x109D2, 0x109FF},
  };

  //! \brief `\p{scx=Meroitic_Hieroglyphs}` — 2 ranges, 33 code points.
  inline constexpr code_range scx_Meroitic_Hieroglyphs_ranges[] {
    {0x205D, 0x205D},
    {0x10980, 0x1099F},
  };

  //! \brief `\p{scx=Miao}` — 3 ranges, 149 code points.
  inline constexpr code_range scx_Miao_ranges[] {
    {0x16F00, 0x16F4A},
    {0x16F4F, 0x16F87},
    {0x16F8F, 0x16F9F},
  };

  //! \brief `\p{scx=Modi}` — 3 ranges, 89 code points.
  inline constexpr code_range scx_Modi_ranges[] {
    {0xA830, 0xA839},
    {0x11600, 0x11644},
    {0x11650, 0x11659},
  };

  //! \brief `\p{scx=Mongolian}` — 7 ranges, 178 code points.
  inline constexpr code_range scx_Mongolian_ranges[] {
    {0x1800, 0x1819},
    {0x1820, 0x1878},
    {0x1880, 0x18AA},
    {0x202F, 0x202F},
    {0x3001, 0x3002},
    {0x3008, 0x300B},
    {0x11660, 0x1166C},
  };

  //! \brief `\p{scx=Mro}` — 3 ranges, 43 code points.
  inline constexpr code_range scx_Mro_ranges[] {
    {0x16A40, 0x16A5E},
    {0x16A60, 0x16A69},
    {0x16A6E, 0x16A6F},
  };

  //! \brief `\p{scx=Multani}` — 6 ranges, 48 code points.
  inline constexpr code_range scx_Multani_ranges[] {
    {0x0A66, 0x0A6F},
    {0x11280, 0x11286},
    {0x11288, 0x11288},
    {0x1128A, 0x1128D},
    {0x1128F, 0x1129D},
    {0x1129F, 0x112A9},
  };

  //! \brief `\p{scx=Myanmar}` — 5 ranges, 244 code points.
  inline constexpr code_range scx_Myanmar_ranges[] {
    {0x1000, 0x109F},
    {0xA92E, 0xA92E},
    {0xA9E0, 0xA9FE},
    {0xAA60, 0xAA7F},
    {0x116D0, 0x116E3},
  };

  //! \brief `\p{scx=Nabataean}` — 2 ranges, 40 code points.
  inline constexpr code_range scx_Nabataean_ranges[] {
    {0x10880, 0x1089E},
    {0x108A7, 0x108AF},
  };

  //! \brief `\p{scx=Nag_Mundari}` — 1 ranges, 42 code points.
  inline constexpr code_range scx_Nag_Mundari_ranges[] {
    {0x1E4D0, 0x1E4F9},
  };

  //! \brief `\p{scx=Nandinagari}` — 9 ranges, 86 code points.
  inline constexpr code_range scx_Nandinagari_ranges[] {
    {0x0964, 0x0965},
    {0x0CE6, 0x0CEF},
    {0x1CE9, 0x1CE9},
    {0x1CF2, 0x1CF2},
    {0x1CFA, 0x1CFA},
    {0xA830, 0xA835},
    {0x119A0, 0x119A7},
    {0x119AA, 0x119D7},
    {0x119DA, 0x119E4},
  };

  //! \brief `\p{scx=New_Tai_Lue}` — 4 ranges, 83 code points.
  inline constexpr code_range scx_New_Tai_Lue_ranges[] {
    {0x1980, 0x19AB},
    {0x19B0, 0x19C9},
    {0x19D0, 0x19DA},
    {0x19DE, 0x19DF},
  };

  //! \brief `\p{scx=Newa}` — 2 ranges, 97 code points.
  inline constexpr code_range scx_Newa_ranges[] {
    {0x11400, 0x1145B},
    {0x1145D, 0x11461},
  };

  //! \brief `\p{scx=Nko}` — 6 ranges, 67 code points.
  inline constexpr code_range scx_Nko_ranges[] {
    {0x060C, 0x060C},
    {0x061B, 0x061B},
    {0x061F, 0x061F},
    {0x07C0, 0x07FA},
    {0x07FD, 0x07FF},
    {0xFD3E, 0xFD3F},
  };

  //! \brief `\p{scx=Nushu}` — 2 ranges, 397 code points.
  inline constexpr code_range scx_Nushu_ranges[] {
    {0x16FE1, 0x16FE1},
    {0x1B170, 0x1B2FB},
  };

  //! \brief `\p{scx=Nyiakeng_Puachue_Hmong}` — 4 ranges, 71 code points.
  inline constexpr code_range scx_Nyiakeng_Puachue_Hmong_ranges[] {
    {0x1E100, 0x1E12C},
    {0x1E130, 0x1E13D},
    {0x1E140, 0x1E149},
    {0x1E14E, 0x1E14F},
  };

  //! \brief `\p{scx=Ogham}` — 1 ranges, 29 code points.
  inline constexpr code_range scx_Ogham_ranges[] {
    {0x1680, 0x169C},
  };

  //! \brief `\p{scx=Ol_Chiki}` — 1 ranges, 48 code points.
  inline constexpr code_range scx_Ol_Chiki_ranges[] {
    {0x1C50, 0x1C7F},
  };

  //! \brief `\p{scx=Ol_Onal}` — 3 ranges, 46 code points.
  inline constexpr code_range scx_Ol_Onal_ranges[] {
    {0x0964, 0x0965},
    {0x1E5D0, 0x1E5FA},
    {0x1E5FF, 0x1E5FF},
  };

  //! \brief `\p{scx=Old_Hungarian}` — 7 ranges, 112 code points.
  inline constexpr code_range scx_Old_Hungarian_ranges[] {
    {0x205A, 0x205A},
    {0x205D, 0x205D},
    {0x2E31, 0x2E31},
    {0x2E41, 0x2E41},
    {0x10C80, 0x10CB2},
    {0x10CC0, 0x10CF2},
    {0x10CFA, 0x10CFF},
  };

  //! \brief `\p{scx=Old_Italic}` — 2 ranges, 39 code points.
  inline constexpr code_range scx_Old_Italic_ranges[] {
    {0x10300, 0x10323},
    {0x1032D, 0x1032F},
  };

  //! \brief `\p{scx=Old_North_Arabian}` — 1 ranges, 32 code points.
  inline constexpr code_range scx_Old_North_Arabian_ranges[] {
    {0x10A80, 0x10A9F},
  };

  //! \brief `\p{scx=Old_Permic}` — 6 ranges, 50 code points.
  inline constexpr code_range scx_Old_Permic_ranges[] {
    {0x00B7, 0x00B7},
    {0x0300, 0x0300},
    {0x0306, 0x0308},
    {0x0313, 0x0313},
    {0x0483, 0x0483},
    {0x10350, 0x1037A},
  };

  //! \brief `\p{scx=Old_Persian}` — 2 ranges, 50 code points.
  inline constexpr code_range scx_Old_Persian_ranges[] {
    {0x103A0, 0x103C3},
    {0x103C8, 0x103D5},
  };

  //! \brief `\p{scx=Old_Sogdian}` — 1 ranges, 40 code points.
  inline constexpr code_range scx_Old_Sogdian_ranges[] {
    {0x10F00, 0x10F27},
  };

  //! \brief `\p{scx=Old_South_Arabian}` — 1 ranges, 32 code points.
  inline constexpr code_range scx_Old_South_Arabian_ranges[] {
    {0x10A60, 0x10A7F},
  };

  //! \brief `\p{scx=Old_Turkic}` — 3 ranges, 75 code points.
  inline constexpr code_range scx_Old_Turkic_ranges[] {
    {0x205A, 0x205A},
    {0x2E30, 0x2E30},
    {0x10C00, 0x10C48},
  };

  //! \brief `\p{scx=Old_Uyghur}` — 3 ranges, 28 code points.
  inline constexpr code_range scx_Old_Uyghur_ranges[] {
    {0x0640, 0x0640},
    {0x10AF2, 0x10AF2},
    {0x10F70, 0x10F89},
  };

  //! \brief `\p{scx=Oriya}` — 18 ranges, 97 code points.
  inline constexpr code_range scx_Oriya_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0B01, 0x0B03},
    {0x0B05, 0x0B0C},
    {0x0B0F, 0x0B10},
    {0x0B13, 0x0B28},
    {0x0B2A, 0x0B30},
    {0x0B32, 0x0B33},
    {0x0B35, 0x0B39},
    {0x0B3C, 0x0B44},
    {0x0B47, 0x0B48},
    {0x0B4B, 0x0B4D},
    {0x0B55, 0x0B57},
    {0x0B5C, 0x0B5D},
    {0x0B5F, 0x0B63},
    {0x0B66, 0x0B77},
    {0x1CDA, 0x1CDA},
    {0x1CF2, 0x1CF2},
  };

  //! \brief `\p{scx=Osage}` — 6 ranges, 76 code points.
  inline constexpr code_range scx_Osage_ranges[] {
    {0x0301, 0x0301},
    {0x0304, 0x0304},
    {0x030B, 0x030B},
    {0x0358, 0x0358},
    {0x104B0, 0x104D3},
    {0x104D8, 0x104FB},
  };

  //! \brief `\p{scx=Osmanya}` — 2 ranges, 40 code points.
  inline constexpr code_range scx_Osmanya_ranges[] {
    {0x10480, 0x1049D},
    {0x104A0, 0x104A9},
  };

  //! \brief `\p{scx=Pahawh_Hmong}` — 5 ranges, 127 code points.
  inline constexpr code_range scx_Pahawh_Hmong_ranges[] {
    {0x16B00, 0x16B45},
    {0x16B50, 0x16B59},
    {0x16B5B, 0x16B61},
    {0x16B63, 0x16B77},
    {0x16B7D, 0x16B8F},
  };

  //! \brief `\p{scx=Palmyrene}` — 1 ranges, 32 code points.
  inline constexpr code_range scx_Palmyrene_ranges[] {
    {0x10860, 0x1087F},
  };

  //! \brief `\p{scx=Pau_Cin_Hau}` — 1 ranges, 57 code points.
  inline constexpr code_range scx_Pau_Cin_Hau_ranges[] {
    {0x11AC0, 0x11AF8},
  };

  //! \brief `\p{scx=Phags_Pa}` — 5 ranges, 61 code points.
  inline constexpr code_range scx_Phags_Pa_ranges[] {
    {0x1802, 0x1803},
    {0x1805, 0x1805},
    {0x202F, 0x202F},
    {0x3002, 0x3002},
    {0xA840, 0xA877},
  };

  //! \brief `\p{scx=Phoenician}` — 2 ranges, 29 code points.
  inline constexpr code_range scx_Phoenician_ranges[] {
    {0x10900, 0x1091B},
    {0x1091F, 0x1091F},
  };

  //! \brief `\p{scx=Psalter_Pahlavi}` — 4 ranges, 30 code points.
  inline constexpr code_range scx_Psalter_Pahlavi_ranges[] {
    {0x0640, 0x0640},
    {0x10B80, 0x10B91},
    {0x10B99, 0x10B9C},
    {0x10BA9, 0x10BAF},
  };

  //! \brief `\p{scx=Rejang}` — 2 ranges, 37 code points.
  inline constexpr code_range scx_Rejang_ranges[] {
    {0xA930, 0xA953},
    {0xA95F, 0xA95F},
  };

  //! \brief `\p{scx=Runic}` — 1 ranges, 89 code points.
  inline constexpr code_range scx_Runic_ranges[] {
    {0x16A0, 0x16F8},
  };

  //! \brief `\p{scx=Samaritan}` — 3 ranges, 62 code points.
  inline constexpr code_range scx_Samaritan_ranges[] {
    {0x0800, 0x082D},
    {0x0830, 0x083E},
    {0x2E31, 0x2E31},
  };

  //! \brief `\p{scx=Saurashtra}` — 2 ranges, 82 code points.
  inline constexpr code_range scx_Saurashtra_ranges[] {
    {0xA880, 0xA8C5},
    {0xA8CE, 0xA8D9},
  };

  //! \brief `\p{scx=Sharada}` — 8 ranges, 109 code points.
  inline constexpr code_range scx_Sharada_ranges[] {
    {0x0951, 0x0951},
    {0x1CD7, 0x1CD7},
    {0x1CD9, 0x1CD9},
    {0x1CDC, 0x1CDD},
    {0x1CE0, 0x1CE0},
    {0xA830, 0xA835},
    {0xA838, 0xA838},
    {0x11180, 0x111DF},
  };

  //! \brief `\p{scx=Shavian}` — 2 ranges, 49 code points.
  inline constexpr code_range scx_Shavian_ranges[] {
    {0x00B7, 0x00B7},
    {0x10450, 0x1047F},
  };

  //! \brief `\p{scx=Siddham}` — 2 ranges, 92 code points.
  inline constexpr code_range scx_Siddham_ranges[] {
    {0x11580, 0x115B5},
    {0x115B8, 0x115DD},
  };

  //! \brief `\p{scx=SignWriting}` — 3 ranges, 672 code points.
  inline constexpr code_range scx_SignWriting_ranges[] {
    {0x1D800, 0x1DA8B},
    {0x1DA9B, 0x1DA9F},
    {0x1DAA1, 0x1DAAF},
  };

  //! \brief `\p{scx=Sinhala}` — 15 ranges, 114 code points.
  inline constexpr code_range scx_Sinhala_ranges[] {
    {0x0964, 0x0965},
    {0x0D81, 0x0D83},
    {0x0D85, 0x0D96},
    {0x0D9A, 0x0DB1},
    {0x0DB3, 0x0DBB},
    {0x0DBD, 0x0DBD},
    {0x0DC0, 0x0DC6},
    {0x0DCA, 0x0DCA},
    {0x0DCF, 0x0DD4},
    {0x0DD6, 0x0DD6},
    {0x0DD8, 0x0DDF},
    {0x0DE6, 0x0DEF},
    {0x0DF2, 0x0DF4},
    {0x1CF2, 0x1CF2},
    {0x111E1, 0x111F4},
  };

  //! \brief `\p{scx=Sogdian}` — 2 ranges, 43 code points.
  inline constexpr code_range scx_Sogdian_ranges[] {
    {0x0640, 0x0640},
    {0x10F30, 0x10F59},
  };

  //! \brief `\p{scx=Sora_Sompeng}` — 2 ranges, 35 code points.
  inline constexpr code_range scx_Sora_Sompeng_ranges[] {
    {0x110D0, 0x110E8},
    {0x110F0, 0x110F9},
  };

  //! \brief `\p{scx=Soyombo}` — 1 ranges, 83 code points.
  inline constexpr code_range scx_Soyombo_ranges[] {
    {0x11A50, 0x11AA2},
  };

  //! \brief `\p{scx=Sundanese}` — 2 ranges, 72 code points.
  inline constexpr code_range scx_Sundanese_ranges[] {
    {0x1B80, 0x1BBF},
    {0x1CC0, 0x1CC7},
  };

  //! \brief `\p{scx=Sunuwar}` — 8 ranges, 51 code points.
  inline constexpr code_range scx_Sunuwar_ranges[] {
    {0x0300, 0x0301},
    {0x0303, 0x0303},
    {0x030D, 0x030D},
    {0x0310, 0x0310},
    {0x032D, 0x032D},
    {0x0331, 0x0331},
    {0x11BC0, 0x11BE1},
    {0x11BF0, 0x11BF9},
  };

  //! \brief `\p{scx=Syloti_Nagri}` — 3 ranges, 57 code points.
  inline constexpr code_range scx_Syloti_Nagri_ranges[] {
    {0x0964, 0x0965},
    {0x09E6, 0x09EF},
    {0xA800, 0xA82C},
  };

  //! \brief `\p{scx=Syriac}` — 19 ranges, 119 code points.
  inline constexpr code_range scx_Syriac_ranges[] {
    {0x0303, 0x0304},
    {0x0307, 0x0308},
    {0x030A, 0x030A},
    {0x0320, 0x0320},
    {0x0323, 0x0325},
    {0x032D, 0x032E},
    {0x0330, 0x0330},
    {0x060C, 0x060C},
    {0x061B, 0x061C},
    {0x061F, 0x061F},
    {0x0640, 0x0640},
    {0x064B, 0x0655},
    {0x0670, 0x0670},
    {0x0700, 0x070D},
    {0x070F, 0x074A},
    {0x074D, 0x074F},
    {0x0860, 0x086A},
    {0x1DF8, 0x1DF8},
    {0x1DFA, 0x1DFA},
  };

  //! \brief `\p{scx=Tagalog}` — 3 ranges, 25 code points.
  inline constexpr code_range scx_Tagalog_ranges[] {
    {0x1700, 0x1715},
    {0x171F, 0x171F},
    {0x1735, 0x1736},
  };

  //! \brief `\p{scx=Tagbanwa}` — 4 ranges, 20 code points.
  inline constexpr code_range scx_Tagbanwa_ranges[] {
    {0x1735, 0x1736},
    {0x1760, 0x176C},
    {0x176E, 0x1770},
    {0x1772, 0x1773},
  };

  //! \brief `\p{scx=Tai_Le}` — 6 ranges, 50 code points.
  inline constexpr code_range scx_Tai_Le_ranges[] {
    {0x0300, 0x0301},
    {0x0307, 0x0308},
    {0x030C, 0x030C},
    {0x1040, 0x1049},
    {0x1950, 0x196D},
    {0x1970, 0x1974},
  };

  //! \brief `\p{scx=Tai_Tham}` — 5 ranges, 127 code points.
  inline constexpr code_range scx_Tai_Tham_ranges[] {
    {0x1A20, 0x1A5E},
    {0x1A60, 0x1A7C},
    {0x1A7F, 0x1A89},
    {0x1A90, 0x1A99},
    {0x1AA0, 0x1AAD},
  };

  //! \brief `\p{scx=Tai_Viet}` — 2 ranges, 72 code points.
  inline constexpr code_range scx_Tai_Viet_ranges[] {
    {0xAA80, 0xAAC2},
    {0xAADB, 0xAADF},
  };

  //! \brief `\p{scx=Takri}` — 4 ranges, 80 code points.
  inline constexpr code_range scx_Takri_ranges[] {
    {0x0964, 0x0965},
    {0xA830, 0xA839},
    {0x11680, 0x116B9},
    {0x116C0, 0x116C9},
  };

  //! \brief `\p{scx=Tamil}` — 25 ranges, 133 code points.
  inline constexpr code_range scx_Tamil_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0B82, 0x0B83},
    {0x0B85, 0x0B8A},
    {0x0B8E, 0x0B90},
    {0x0B92, 0x0B95},
    {0x0B99, 0x0B9A},
    {0x0B9C, 0x0B9C},
    {0x0B9E, 0x0B9F},
    {0x0BA3, 0x0BA4},
    {0x0BA8, 0x0BAA},
    {0x0BAE, 0x0BB9},
    {0x0BBE, 0x0BC2},
    {0x0BC6, 0x0BC8},
    {0x0BCA, 0x0BCD},
    {0x0BD0, 0x0BD0},
    {0x0BD7, 0x0BD7},
    {0x0BE6, 0x0BFA},
    {0x1CDA, 0x1CDA},
    {0xA8F3, 0xA8F3},
    {0x11301, 0x11301},
    {0x11303, 0x11303},
    {0x1133B, 0x1133C},
    {0x11FC0, 0x11FF1},
    {0x11FFF, 0x11FFF},
  };

  //! \brief `\p{scx=Tangsa}` — 2 ranges, 89 code points.
  inline constexpr code_range scx_Tangsa_ranges[] {
    {0x16A70, 0x16ABE},
    {0x16AC0, 0x16AC9},
  };

  //! \brief `\p{scx=Tangut}` — 6 ranges, 6931 code points.
  inline constexpr code_range scx_Tangut_ranges[] {
    {0x2FF0, 0x2FFF},
    {0x31EF, 0x31EF},
    {0x16FE0, 0x16FE0},
    {0x17000, 0x187F7},
    {0x18800, 0x18AFF},
    {0x18D00, 0x18D08},
  };

  //! \brief `\p{scx=Telugu}` — 17 ranges, 106 code points.
  inline constexpr code_range scx_Telugu_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x0C00, 0x0C0C},
    {0x0C0E, 0x0C10},
    {0x0C12, 0x0C28},
    {0x0C2A, 0x0C39},
    {0x0C3C, 0x0C44},
    {0x0C46, 0x0C48},
    {0x0C4A, 0x0C4D},
    {0x0C55, 0x0C56},
    {0x0C58, 0x0C5A},
    {0x0C5D, 0x0C5D},
    {0x0C60, 0x0C63},
    {0x0C66, 0x0C6F},
    {0x0C77, 0x0C7F},
    {0x1CDA, 0x1CDA},
    {0x1CF2, 0x1CF2},
  };

  //! \brief `\p{scx=Thaana}` — 7 ranges, 66 code points.
  inline constexpr code_range scx_Thaana_ranges[] {
    {0x060C, 0x060C},
    {0x061B, 0x061C},
    {0x061F, 0x061F},
    {0x0660, 0x0669},
    {0x0780, 0x07B1},
    {0xFDF2, 0xFDF2},
    {0xFDFD, 0xFDFD},
  };

  //! \brief `\p{scx=Thai}` — 6 ranges, 90 code points.
  inline constexpr code_range scx_Thai_ranges[] {
    {0x02BC, 0x02BC},
    {0x02D7, 0x02D7},
    {0x0303, 0x0303},
    {0x0331, 0x0331},
    {0x0E01, 0x0E3A},
    {0x0E40, 0x0E5B},
  };

  //! \brief `\p{scx=Tibetan}` — 8 ranges, 211 code points.
  inline constexpr code_range scx_Tibetan_ranges[] {
    {0x0F00, 0x0F47},
    {0x0F49, 0x0F6C},
    {0x0F71, 0x0F97},
    {0x0F99, 0x0FBC},
    {0x0FBE, 0x0FCC},
    {0x0FCE, 0x0FD4},
    {0x0FD9, 0x0FDA},
    {0x3008, 0x300B},
  };

  //! \brief `\p{scx=Tifinagh}` — 7 ranges, 63 code points.
  inline constexpr code_range scx_Tifinagh_ranges[] {
    {0x0302, 0x0302},
    {0x0304, 0x0304},
    {0x0307, 0x0307},
    {0x0309, 0x0309},
    {0x2D30, 0x2D67},
    {0x2D6F, 0x2D70},
    {0x2D7F, 0x2D7F},
  };

  //! \brief `\p{scx=Tirhuta}` — 6 ranges, 97 code points.
  inline constexpr code_range scx_Tirhuta_ranges[] {
    {0x0951, 0x0952},
    {0x0964, 0x0965},
    {0x1CF2, 0x1CF2},
    {0xA830, 0xA839},
    {0x11480, 0x114C7},
    {0x114D0, 0x114D9},
  };

  //! \brief `\p{scx=Todhri}` — 7 ranges, 58 code points.
  inline constexpr code_range scx_Todhri_ranges[] {
    {0x0301, 0x0301},
    {0x0304, 0x0304},
    {0x0307, 0x0307},
    {0x0311, 0x0311},
    {0x0313, 0x0313},
    {0x035E, 0x035E},
    {0x105C0, 0x105F3},
  };

  //! \brief `\p{scx=Toto}` — 2 ranges, 32 code points.
  inline constexpr code_range scx_Toto_ranges[] {
    {0x02BC, 0x02BC},
    {0x1E290, 0x1E2AE},
  };

  //! \brief `\p{scx=Tulu_Tigalari}` — 16 ranges, 99 code points.
  inline constexpr code_range scx_Tulu_Tigalari_ranges[] {
    {0x0CE6, 0x0CEF},
    {0x1CF2, 0x1CF2},
    {0x1CF4, 0x1CF4},
    {0xA830, 0xA835},
    {0xA8F1, 0xA8F1},
    {0x11380, 0x11389},
    {0x1138B, 0x1138B},
    {0x1138E, 0x1138E},
    {0x11390, 0x113B5},
    {0x113B7, 0x113C0},
    {0x113C2, 0x113C2},
    {0x113C5, 0x113C5},
    {0x113C7, 0x113CA},
    {0x113CC, 0x113D5},
    {0x113D7, 0x113D8},
    {0x113E1, 0x113E2},
  };

  //! \brief `\p{scx=Ugaritic}` — 2 ranges, 31 code points.
  inline constexpr code_range scx_Ugaritic_ranges[] {
    {0x10380, 0x1039D},
    {0x1039F, 0x1039F},
  };

  //! \brief `\p{scx=Vai}` — 1 ranges, 300 code points.
  inline constexpr code_range scx_Vai_ranges[] {
    {0xA500, 0xA62B},
  };

  //! \brief `\p{scx=Vithkuqi}` — 8 ranges, 70 code points.
  inline constexpr code_range scx_Vithkuqi_ranges[] {
    {0x10570, 0x1057A},
    {0x1057C, 0x1058A},
    {0x1058C, 0x10592},
    {0x10594, 0x10595},
    {0x10597, 0x105A1},
    {0x105A3, 0x105B1},
    {0x105B3, 0x105B9},
    {0x105BB, 0x105BC},
  };

  //! \brief `\p{scx=Wancho}` — 2 ranges, 59 code points.
  inline constexpr code_range scx_Wancho_ranges[] {
    {0x1E2C0, 0x1E2F9},
    {0x1E2FF, 0x1E2FF},
  };

  //! \brief `\p{scx=Warang_Citi}` — 2 ranges, 84 code points.
  inline constexpr code_range scx_Warang_Citi_ranges[] {
    {0x118A0, 0x118F2},
    {0x118FF, 0x118FF},
  };

  //! \brief `\p{scx=Yezidi}` — 7 ranges, 60 code points.
  inline constexpr code_range scx_Yezidi_ranges[] {
    {0x060C, 0x060C},
    {0x061B, 0x061B},
    {0x061F, 0x061F},
    {0x0660, 0x0669},
    {0x10E80, 0x10EA9},
    {0x10EAB, 0x10EAD},
    {0x10EB0, 0x10EB1},
  };

  //! \brief `\p{scx=Yi}` — 7 ranges, 1246 code points.
  inline constexpr code_range scx_Yi_ranges[] {
    {0x3001, 0x3002},
    {0x3008, 0x3011},
    {0x3014, 0x301B},
    {0x30FB, 0x30FB},
    {0xA000, 0xA48C},
    {0xA490, 0xA4C6},
    {0xFF61, 0xFF65},
  };

  //! \brief `\p{scx=Zanabazar_Square}` — 1 ranges, 72 code points.
  inline constexpr code_range scx_Zanabazar_Square_ranges[] {
    {0x11A00, 0x11A47},
  };

  //! \brief Range table indexed by \ref script (parallel to the enum order, `Unknown` empty --
  //!        no code point's scx is ever explicitly Unknown, see the generator).
  inline constexpr std::span<const code_range> scx_ranges[] {
    {}, // script::Unknown -- never a member of any scx (ScriptExtensions.txt never lists it)
    scx_Adlam_ranges,
    scx_Ahom_ranges,
    scx_Anatolian_Hieroglyphs_ranges,
    scx_Arabic_ranges,
    scx_Armenian_ranges,
    scx_Avestan_ranges,
    scx_Balinese_ranges,
    scx_Bamum_ranges,
    scx_Bassa_Vah_ranges,
    scx_Batak_ranges,
    scx_Bengali_ranges,
    scx_Bhaiksuki_ranges,
    scx_Bopomofo_ranges,
    scx_Brahmi_ranges,
    scx_Braille_ranges,
    scx_Buginese_ranges,
    scx_Buhid_ranges,
    scx_Canadian_Aboriginal_ranges,
    scx_Carian_ranges,
    scx_Caucasian_Albanian_ranges,
    scx_Chakma_ranges,
    scx_Cham_ranges,
    scx_Cherokee_ranges,
    scx_Chorasmian_ranges,
    scx_Common_ranges,
    scx_Coptic_ranges,
    scx_Cuneiform_ranges,
    scx_Cypriot_ranges,
    scx_Cypro_Minoan_ranges,
    scx_Cyrillic_ranges,
    scx_Deseret_ranges,
    scx_Devanagari_ranges,
    scx_Dives_Akuru_ranges,
    scx_Dogra_ranges,
    scx_Duployan_ranges,
    scx_Egyptian_Hieroglyphs_ranges,
    scx_Elbasan_ranges,
    scx_Elymaic_ranges,
    scx_Ethiopic_ranges,
    scx_Garay_ranges,
    scx_Georgian_ranges,
    scx_Glagolitic_ranges,
    scx_Gothic_ranges,
    scx_Grantha_ranges,
    scx_Greek_ranges,
    scx_Gujarati_ranges,
    scx_Gunjala_Gondi_ranges,
    scx_Gurmukhi_ranges,
    scx_Gurung_Khema_ranges,
    scx_Han_ranges,
    scx_Hangul_ranges,
    scx_Hanifi_Rohingya_ranges,
    scx_Hanunoo_ranges,
    scx_Hatran_ranges,
    scx_Hebrew_ranges,
    scx_Hiragana_ranges,
    scx_Imperial_Aramaic_ranges,
    scx_Inherited_ranges,
    scx_Inscriptional_Pahlavi_ranges,
    scx_Inscriptional_Parthian_ranges,
    scx_Javanese_ranges,
    scx_Kaithi_ranges,
    scx_Kannada_ranges,
    scx_Katakana_ranges,
    scx_Kawi_ranges,
    scx_Kayah_Li_ranges,
    scx_Kharoshthi_ranges,
    scx_Khitan_Small_Script_ranges,
    scx_Khmer_ranges,
    scx_Khojki_ranges,
    scx_Khudawadi_ranges,
    scx_Kirat_Rai_ranges,
    scx_Lao_ranges,
    scx_Latin_ranges,
    scx_Lepcha_ranges,
    scx_Limbu_ranges,
    scx_Linear_A_ranges,
    scx_Linear_B_ranges,
    scx_Lisu_ranges,
    scx_Lycian_ranges,
    scx_Lydian_ranges,
    scx_Mahajani_ranges,
    scx_Makasar_ranges,
    scx_Malayalam_ranges,
    scx_Mandaic_ranges,
    scx_Manichaean_ranges,
    scx_Marchen_ranges,
    scx_Masaram_Gondi_ranges,
    scx_Medefaidrin_ranges,
    scx_Meetei_Mayek_ranges,
    scx_Mende_Kikakui_ranges,
    scx_Meroitic_Cursive_ranges,
    scx_Meroitic_Hieroglyphs_ranges,
    scx_Miao_ranges,
    scx_Modi_ranges,
    scx_Mongolian_ranges,
    scx_Mro_ranges,
    scx_Multani_ranges,
    scx_Myanmar_ranges,
    scx_Nabataean_ranges,
    scx_Nag_Mundari_ranges,
    scx_Nandinagari_ranges,
    scx_New_Tai_Lue_ranges,
    scx_Newa_ranges,
    scx_Nko_ranges,
    scx_Nushu_ranges,
    scx_Nyiakeng_Puachue_Hmong_ranges,
    scx_Ogham_ranges,
    scx_Ol_Chiki_ranges,
    scx_Ol_Onal_ranges,
    scx_Old_Hungarian_ranges,
    scx_Old_Italic_ranges,
    scx_Old_North_Arabian_ranges,
    scx_Old_Permic_ranges,
    scx_Old_Persian_ranges,
    scx_Old_Sogdian_ranges,
    scx_Old_South_Arabian_ranges,
    scx_Old_Turkic_ranges,
    scx_Old_Uyghur_ranges,
    scx_Oriya_ranges,
    scx_Osage_ranges,
    scx_Osmanya_ranges,
    scx_Pahawh_Hmong_ranges,
    scx_Palmyrene_ranges,
    scx_Pau_Cin_Hau_ranges,
    scx_Phags_Pa_ranges,
    scx_Phoenician_ranges,
    scx_Psalter_Pahlavi_ranges,
    scx_Rejang_ranges,
    scx_Runic_ranges,
    scx_Samaritan_ranges,
    scx_Saurashtra_ranges,
    scx_Sharada_ranges,
    scx_Shavian_ranges,
    scx_Siddham_ranges,
    scx_SignWriting_ranges,
    scx_Sinhala_ranges,
    scx_Sogdian_ranges,
    scx_Sora_Sompeng_ranges,
    scx_Soyombo_ranges,
    scx_Sundanese_ranges,
    scx_Sunuwar_ranges,
    scx_Syloti_Nagri_ranges,
    scx_Syriac_ranges,
    scx_Tagalog_ranges,
    scx_Tagbanwa_ranges,
    scx_Tai_Le_ranges,
    scx_Tai_Tham_ranges,
    scx_Tai_Viet_ranges,
    scx_Takri_ranges,
    scx_Tamil_ranges,
    scx_Tangsa_ranges,
    scx_Tangut_ranges,
    scx_Telugu_ranges,
    scx_Thaana_ranges,
    scx_Thai_ranges,
    scx_Tibetan_ranges,
    scx_Tifinagh_ranges,
    scx_Tirhuta_ranges,
    scx_Todhri_ranges,
    scx_Toto_ranges,
    scx_Tulu_Tigalari_ranges,
    scx_Ugaritic_ranges,
    scx_Vai_ranges,
    scx_Vithkuqi_ranges,
    scx_Wancho_ranges,
    scx_Warang_Citi_ranges,
    scx_Yezidi_ranges,
    scx_Yi_ranges,
    scx_Zanabazar_Square_ranges,
  };

  /*!
   * \brief Whether \p cp is in the Script_Extensions of \p sc (== the UCD). NOT exclusive:
   *        a code point can satisfy this for several \ref script values at once.
   * \param[in] sc The Script to test for.
   * \param[in] cp The code point to test.
   * \return Whether \p sc is in \p cp's Script_Extensions set.
   */
  constexpr bool is_scx_cp(script sc, char32_t cp)
  {
    return cp_in_ranges(scx_ranges[static_cast<std::size_t>(sc)], cp);
  }

} // namespace real::detail

#endif // REAL_UNICODE_SCX_HPP
