[package]
name = "RustWorker"
version = "2.0.0"
edition = "2021"
authors = ["Viorel <Viorel@noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
json = "0.12.4"
rustc_version_runtime = "0.3.0"

