[package]
name = "RustRegexLiteWorker"
version = "2.0.0"
edition = "2021"
authors = ["Viorel <Viorel@noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
regex-lite = "0.1.7"
